import React from 'react';
import {
  Heart,
  Star,
  Sparkles,
  Flame,
  Lightbulb,
  User,
  Cloud,
  Database,
  Code,
  Shield,
  MessageSquare,
  ThumbsUp,
  AlertCircle,
  Rocket,
  Smile,
  Compass,
  CheckCircle2,
  Zap,
  Trophy,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Clock,
  Cpu,
  FileText,
  Folder,
  Globe,
  Home,
  Image,
  Key,
  Link2,
  Lock,
  Mail,
  MapPin,
  Music,
  Phone,
  Pin,
  Send,
  Server,
  Share2,
  ShoppingCart,
  Tag,
  Terminal,
  Coffee,
  Gift,
  Flag,
  Wifi,
  Target,
  Layers,
  Search,
  Sun,
  Moon,
  Eye,
  HelpCircle,
} from 'lucide-react';

export interface IconConfig {
  label: string;
  keywords: string[];
  component: React.FC<{ className?: string; size?: number; color?: string }>;
}

export const AVAILABLE_ICONS: Record<string, IconConfig> = {
  star: { label: 'Star', keywords: ['star', 'favorite', 'rating', 'rate', 'badge', 'award'], component: Star },
  heart: { label: 'Heart', keywords: ['heart', 'love', 'like', 'health', 'favorite'], component: Heart },
  sparkles: { label: 'Sparkles', keywords: ['sparkles', 'magic', 'ai', 'clean', 'special', 'shine'], component: Sparkles },
  flame: { label: 'Flame', keywords: ['flame', 'fire', 'hot', 'trending', 'burn'], component: Flame },
  lightbulb: { label: 'Idea', keywords: ['idea', 'lightbulb', 'inspire', 'solution', 'bright', 'innovation'], component: Lightbulb },
  zap: { label: 'Lightning', keywords: ['zap', 'lightning', 'energy', 'power', 'fast', 'speed', 'charge'], component: Zap },
  trophy: { label: 'Trophy', keywords: ['trophy', 'win', 'award', 'first', 'champion', 'success'], component: Trophy },
  target: { label: 'Target', keywords: ['target', 'goal', 'bullseye', 'aim', 'focus', 'objective'], component: Target },
  user: { label: 'User', keywords: ['user', 'person', 'profile', 'account', 'avatar', 'member'], component: User },
  smile: { label: 'Smile', keywords: ['smile', 'happy', 'emoji', 'face', 'fun', 'joy'], component: Smile },
  'thumbs-up': { label: 'Like', keywords: ['like', 'thumbs', 'up', 'approve', 'agree', 'good', 'yes'], component: ThumbsUp },
  rocket: { label: 'Rocket', keywords: ['rocket', 'launch', 'startup', 'ship', 'speed', 'fly', 'fast'], component: Rocket },
  cloud: { label: 'Cloud', keywords: ['cloud', 'storage', 'weather', 'server', 'online', 'sync'], component: Cloud },
  database: { label: 'Database', keywords: ['database', 'data', 'sql', 'storage', 'backend', 'table'], component: Database },
  server: { label: 'Server', keywords: ['server', 'rack', 'backend', 'network', 'host', 'system'], component: Server },
  code: { label: 'Code', keywords: ['code', 'developer', 'program', 'html', 'tech', 'bracket'], component: Code },
  terminal: { label: 'Terminal', keywords: ['terminal', 'console', 'cli', 'bash', 'command', 'prompt'], component: Terminal },
  cpu: { label: 'Processor', keywords: ['cpu', 'processor', 'chip', 'hardware', 'hardware', 'tech'], component: Cpu },
  shield: { label: 'Shield', keywords: ['shield', 'security', 'protect', 'safe', 'secure', 'guard'], component: Shield },
  lock: { label: 'Lock', keywords: ['lock', 'security', 'private', 'password', 'protect'], component: Lock },
  key: { label: 'Key', keywords: ['key', 'access', 'auth', 'unlock', 'token'], component: Key },
  message: { label: 'Chat', keywords: ['chat', 'message', 'comment', 'discussion', 'bubble', 'talk'], component: MessageSquare },
  mail: { label: 'Mail', keywords: ['mail', 'email', 'inbox', 'letter', 'send'], component: Mail },
  send: { label: 'Send', keywords: ['send', 'paperplane', 'submit', 'message', 'deliver'], component: Send },
  bell: { label: 'Notification', keywords: ['bell', 'alert', 'notification', 'reminder', 'alarm'], component: Bell },
  bookmark: { label: 'Bookmark', keywords: ['bookmark', 'save', 'ribbon', 'favorite', 'tag'], component: Bookmark },
  calendar: { label: 'Calendar', keywords: ['calendar', 'date', 'schedule', 'event', 'plan', 'time'], component: Calendar },
  clock: { label: 'Clock', keywords: ['clock', 'time', 'hour', 'timer', 'watch', 'duration'], component: Clock },
  compass: { label: 'Compass', keywords: ['compass', 'direction', 'explore', 'navigation', 'guide'], component: Compass },
  'map-pin': { label: 'Location', keywords: ['location', 'map', 'pin', 'place', 'gps', 'address'], component: MapPin },
  globe: { label: 'Web', keywords: ['globe', 'earth', 'world', 'web', 'internet', 'global'], component: Globe },
  home: { label: 'Home', keywords: ['home', 'house', 'main', 'start', 'page'], component: Home },
  image: { label: 'Image', keywords: ['image', 'photo', 'picture', 'gallery', 'graphic'], component: Image },
  camera: { label: 'Camera', keywords: ['camera', 'photo', 'capture', 'video', 'lens'], component: Camera },
  music: { label: 'Music', keywords: ['music', 'song', 'audio', 'sound', 'melody'], component: Music },
  phone: { label: 'Phone', keywords: ['phone', 'call', 'contact', 'mobile', 'cell'], component: Phone },
  pin: { label: 'Pin', keywords: ['pin', 'tack', 'sticky', 'board', 'marker'], component: Pin },
  share: { label: 'Share', keywords: ['share', 'export', 'forward', 'distribute'], component: Share2 },
  link: { label: 'Link', keywords: ['link', 'chain', 'url', 'connect', 'attachment'], component: Link2 },
  cart: { label: 'Cart', keywords: ['cart', 'shop', 'shopping', 'buy', 'store', 'checkout'], component: ShoppingCart },
  tag: { label: 'Tag', keywords: ['tag', 'label', 'price', 'category', 'badge'], component: Tag },
  file: { label: 'Document', keywords: ['file', 'doc', 'document', 'text', 'paper', 'page'], component: FileText },
  folder: { label: 'Folder', keywords: ['folder', 'directory', 'organize', 'files', 'storage'], component: Folder },
  layers: { label: 'Layers', keywords: ['layers', 'stack', 'overlay', 'hierarchy', 'design'], component: Layers },
  coffee: { label: 'Coffee', keywords: ['coffee', 'tea', 'cup', 'break', 'drink', 'morning'], component: Coffee },
  gift: { label: 'Gift', keywords: ['gift', 'present', 'reward', 'box', 'holiday', 'bonus'], component: Gift },
  flag: { label: 'Flag', keywords: ['flag', 'mark', 'goal', 'country', 'milestone', 'report'], component: Flag },
  wifi: { label: 'Wifi', keywords: ['wifi', 'wireless', 'network', 'internet', 'connection'], component: Wifi },
  sun: { label: 'Sun', keywords: ['sun', 'day', 'light', 'bright', 'weather', 'morning'], component: Sun },
  moon: { label: 'Moon', keywords: ['moon', 'night', 'dark', 'sleep', 'evening'], component: Moon },
  eye: { label: 'Eye', keywords: ['eye', 'view', 'watch', 'see', 'preview', 'visibility'], component: Eye },
  search: { label: 'Search', keywords: ['search', 'find', 'lookup', 'magnifier', 'explore'], component: Search },
  check: { label: 'Done', keywords: ['check', 'done', 'tick', 'verify', 'complete', 'success'], component: CheckCircle2 },
  alert: { label: 'Warning', keywords: ['alert', 'warning', 'danger', 'caution', 'notice', 'issue'], component: AlertCircle },
  help: { label: 'Help', keywords: ['help', 'question', 'support', 'faq', 'info'], component: HelpCircle },
};
